### ISSUE TITLE
Upgrading from 3.3.2 to 4.5.0

### ISSUE THREAD

**Issue by Xmansec** [OpenCTI-Platform/migration_script_v4#6]
When I upgrade from 3.3.2 to 4.5.0 I found that some data were lost, such as some notes and users. In addition, I found the following error in worker, and I don't know whether it is related to it.

`
worker                                 | ERROR:root:[opencti_observedData] Missing parameters: first_observed or last_observed

worker                                 | ERROR:root:'list' object has no attribute 'items'
`
